### ISSUE TITLE
The `insert_range` method does not properly handle boundary condition

### ISSUE THREAD

**Issue by oliverdding** [RoaringBitmap/roaring-rs#113]
## Progress

* [x] Switch inner parameters to RangeBounds
  * [x] insert_range
  * [x] remove_range
* [x] Fix boundary condition in insert_range/remove_range
* [x] Add more tests

## Experiments

```rust
#[test]
fn insert_range_multi() {
    let mut bitmap = RoaringBitmap::new();
    bitmap.insert_range(0..((1_u64 << 16) + 1));
    println!("{:?}", bitmap);
}

#[test]
fn insert_multi() {
    let mut bitmap = RoaringBitmap::new();
    for i in 0..((1 << 16) + 1) {
        bitmap.insert(i);
    }
    println!("{:?}", bitmap);
}

#[test]
fn insert_range_single() {
    let mut bitmap = RoaringBitmap::new();
    bitmap.insert_range(0..(1_u64 << 16));
    println!("{:?}", bitmap); // would panic here
}

#[test]
fn insert_single() {
    let mut bitmap = RoaringBitmap::new();
    for i in 0..(1 << 16) {
        bitmap.insert(i);
    }
    println!("{:?}", bitmap);
}
```

## single partition insertion

After insert 0..(1_u64 << 16) to the bitmap, we expect only one container(bitmap), whose key is 0, exists in the bitmap.

But actually we got:

![insert_range_single](https://user-images.githubusercontent.com/43624923/130414640-8775f601-aa20-4294-93c2-3fc722b1c7ef.png)

## multiply partition insertion

After insert 0..((1_u64 << 16) + 1) to the bitmap, we expect one container(bitmap), whose key is 0, followed by a container(array), whose key is 1.

But we got:

![insert_range_multi](https://user-images.githubusercontent.com/43624923/130415192-7fd3c201-5bc2-4725-96f5-f3a1d70fb204.png)

**Comment by Kerollmops** [comment]
Hey @oliverdding, have you found the time to work on this? 😃

**Comment by oliverdding** [comment]
Hi @Kerollmops , yes, sure. Maybe I have misunderstood ( I'm waiting for your [PR](https://github.com/RoaringBitmap/roaring-rs/pull/92) on `RangeBound` XP).

Anyway, let's see what I can do now. I can modify inner `insert_range` without breaking outside's `insert_range`, is that right?

Inner function's declaration should be changed, in which case should I use `RangeInclusive ` or `RangeBound` to keep consistency with you?

**Comment by Kerollmops** [comment]
In fact, I am not sure if we really care to break or not, go on break everything, we will simply release a new breaking version 😄

You can use [the `RangeBounds` trait](https://doc.rust-lang.org/std/ops/trait.RangeBounds.html) on the user-facing API i.e `RoaringBitmap/RoaringTreemap::insert_range` if it's not too complex, it would be ideal or [the `RangeInclusive` struct](https://doc.rust-lang.org/std/ops/struct.RangeInclusive.html), like you said if that too much work. 🚀

**Comment by oliverdding** [comment]
May I ask a question, where is the best place to put the test case? I found that in roaring-rs they are ling across the source file and tests folder.

**Comment by oliverdding** [comment]
Hi @Kerollmops 

I got you. Here is my idea:

I work on switching `Range` to `RangeInclusive` for `Container` and `Store` based on your branch, which is internal. This can be committed with your [Rework the insert/remove_range functions with RangeBounds #92](https://github.com/RoaringBitmap/roaring-rs/pull/92).

After that, I can fix boundary issue.

**Comment by Kerollmops** [comment]
Hey @oliverdding,

Seems like a great idea, go on I will take time to review that! And no worries about your English it's very good 😃

**Comment by oliverdding** [comment]
Hi @Kerollmops 

I've push another fix based on your branch, which trying to use `RangeBounds` as parameter.

But I encountered a problems:

In rust std-lib, `RangeBounds` are always used with `<usize>`, but I think a solid boundary is much more meaningful in our scenario, preventing boundary check. What do you think?

**Comment by Kerollmops** [comment]
> Hi @Kerollmops 
> 
> 
> 
> I've pushed another fix based on your branch(you can find it [here](https://github.com/oliverdding/roaring-rs/tree/inner-range-inclusive)), trying to use `RangeBounds` as parameter to fix inner `insert_range` and `remove_range` method.

I like what you have done, I didn't find time to review it in details but what I can see is that you changed a little bit too much things in this commit, for example you modifies the `!0u64` to `u64::MAX` and things like that. You also changed/added new tests in this commit. I would prefer that you split the changes in multiple commits and also don't touch too much to the current logic. It would be much easier for me to review bit by bit your changes 😄

> 1. In rust std-lib, `RangeBounds` are always used with `<usize>`, but I think a solid boundary is much more meaningful in our scenario, preventing boundary check. What do you think?

I think the user-side API must, indeed, expose a `RangeBounds<u32>` for the Bitmap and a `RangeBounds<u64>` for the `Treemap`.

> 2. Though we use `RangeBounds`, which has three types in both boundary. But, in fact, only Range( [a, b) ) and RangeInclusive( [a, b] ) are effective, am I right?

It would be easier to just support all of them, as we know the real boundaries i.e `u32::MIN` and `u32::MAX`, we fan easily convert unbounded ranges to fully bounded ones.

**Comment by oliverdding** [comment]
> I would prefer that you split the changes in multiple commits and also don't touch too much to the current logic.

Ok, I would re-arange my code and commit later into a new branch.

> I think the user-side API must, indeed, expose a RangeBounds<u32> for the Bitmap and a RangeBounds<u64> for the Treemap.

In my mind, it should be `u16` for the inner insert_range, just like what I have done. And as what your mentioned, It should be `u32`/`u64` in the user-side API. And for now, I just handle with the inner side.

> It would be easier to just support all of them, as we know the real boundaries i.e u32::MIN and u32::MAX, we can easily convert unbounded ranges to fully bounded ones.

This is confusing. I can only find two kind of parameters that user would passwd in:

1. `insert_range(1..2)` which have left Included and right Excluded.
2. `insert_range(1..=2)` which have lefet Included and right Included.

And I have handled both of the situation I mentioned below.

The point is `Outbounded`, in which scenario this would happen? And when it happen how can I scale down it's boundary to `Included` in both side?

**Comment by Kerollmops** [comment]
> In my mind, it should be `u16` for the inner insert_range, just like what I have done. And as what your mentioned, It should be `u32`/`u64` in the user-side API. And for now, I just handle with the inner side.

Yup, that's it!

> This is confusing. I can only find two kind of parameters that user would passwd in:
> 
>  1. `insert_range(1..2)` which have left Included and right Excluded.
>
>  2. `insert_range(1..=2)` which have lefet Included and right Included.
>
> And I have handled both of the situation I mentioned below.
>
> The point is `Outbounded`, in which scenario this would happen? And when it happen how can I scale down it's boundary to `Included` in both side?

A user could also use unbounded ranges like so:
   1.  `insert_range(..20)` which have left unbounded and right excluded which is equivalent to `insert_range(0..20)`.
   1.  `insert_range(..0)` which have left unbounded and right excluded which is equivalent to ignoring the call as nothing can be inserted, zero is excluded.
   1. `insert_range(20..)` which have left included and right unbounded which is equivalent to `insert_range(20..=u32::MAX)`.
   1.  `insert_range(u32::MAX..)` which have left included and right unbound which is equivalent to just inserting `u32::MAX` but also simply equivalent to the range described above (3.).

And this is why I told you that all of these other situations can be easily converted into both included bounds. And if the user specifies an empty range, we can early return as nothing can be inserted.

**Comment by oliverdding** [comment]
Hi @Kerollmops

I finally finished the job, moving inner's range related functions to accept `RangeBounds`, perfectly handling all boundary conditions. I have created a neo-branch to commit minimal changes that fix this issue, all of the changes can be seen in this [PR](https://github.com/RoaringBitmap/roaring-rs/pull/114).

(BTW, I proposed to switching `max_value()` to `MAX`, which is deprecated.

**Comment by oliverdding** [comment]
Hi @Kerollmops 

When fixing this issue, I am confused of the `pub` of functions of store and container.

In my mind, they should never be exposed to the end-user, it that right?

**Comment by Kerollmops** [comment]
Yup, that's right but `pub` doesn't mean it is exposed to the user, it means it is expose out of the module, and as you can see we never expose the `Store` or `Container` type out of the `lib.rs`. So yeah, the `pub` in front of the `Store` and `Container` methods means: expose this out of the module not out of the `lib.rs`. So that's private to everyone that can't see the types.

PS: You can check that the types are private by doing a simple `cargo doc --open`.

**Comment by oliverdding** [comment]
Hi @Kerollmops . I got it.

And now I have done all the tasks and created another PR now.

Thanks for your patience 😊
