### ISSUE TITLE
v0.8.0 Subtraction of two bitmaps gives wrong bitmap

### ISSUE THREAD

**Issue by kolstae** [RoaringBitmap/roaring-rs#117]
sub_assign works as expected while subtract doesn't
```rust
    #[test]
    fn test_rbm_sub() {
        let all: RoaringBitmap = (0..5000).collect();
        let all_len = all.len();
        let some = RoaringBitmap::from_iter(all.iter().filter(|i| *i % 7 == 0));
        let rest = &all - &some;
        let rest2 = all - &some;

        assert_eq!(all_len, some.len() + rest2.len());
        assert_eq!(rest2.len(), rest.len()); // Fails with Left: 4285 Right: 5000
    }
```
When creating a smaller bitmap e.g. `4000`, subtract works as expected.

**Comment by ManyTheFish** [comment]
Hey @kolstae, you are right, there is a bug in [the `sub` function in `store.rs`](https://github.com/RoaringBitmap/roaring-rs/blob/25728f2179dbcf1dcd08a7be575436db4440d8a7/src/bitmap/store.rs#L499) 

that should be:
```diff
- BitOrAssign::bitor_assign(&mut lhs, rhs);
+ SubAssign::sub_assign(&mut lhs, rhs);
```
Unfortunately, I can't fix it this week. 
Could you please create a PR adding your test and trying the fix?

Thanks a lot for your issue! 🙂

**Comment by kolstae** [comment]
Sure :)
