### ISSUE TITLE
Sample data for benchmarking

### ISSUE THREAD

**Issue by saik0** [RoaringBitmap/roaring-rs#129]
## Summary

The build.rs script fetches one of sample datasets (`wikileaks-noquotes_srt`) on each run. 

_This request is for _some_ mechanism be to have _all_ the datasets in `RoaringBitmap/real-roaring-datasets` reliably available for benchmarking._

## Rationale

It would be helpful to have a canonical perf baseline to ensure new work does not introduce performance regressions.

Many of our existing benchmarks use data that is trivially predicted by the branch predictor. Unfortunately this makes them worse than useless: We are benchmarking the CPU branch predictor rather than our code.

To remedy this: I've been working on a benchmark suite that uses all the sample datasets. Here's a sneak peek of a subset of the report.

![Screen Shot 2022-01-09 at 6 19 36 PM](https://user-images.githubusercontent.com/997050/148711553-82395abf-5b2b-4083-81ac-4c73606f8206.png)

In order for this to be able to be merged, we would need the datasets to be available to the benchmark suite.

## Problems with the current approach:
 * Fetches the datasets specified in build.rs on _every build_
 * Only fetches one dataset

## Potential solutions
 * Check in the unzipped data sets into the repo.
 * Check in the zip files into the repo, unpack them in build.rs
 * Include `RoaringBitmap/real-roaring-datasets` as a git submodule (leave it up to the developer to `git submodule update`) if they want to run benchmarks
 * Add some statefulness to `benchmarks/build.rs` that only fetches when necessary
   * IMO, I like this one least as it's the most work and feels alot like reimplementing `git` or `rsync`

## Considerations
 * How will any potential solution effect CI builds?
 * Could the datasets also be useful for unit testing?

**Comment by Kerollmops** [comment]
That would be great indeed, making sure that all of the datasets are available to the benchmark suite. I think that my preferred attempt to do so would be the one with the _git submodule_, it seems like the easiest one to implement and to use, a simple `git submodule init/update`.

However, we _must_ absolutely make sure that the README of the benchmark crate lists the command to run before running the benchmarks. I am absolutely not comfortable enough with git submodules to be sure to not make a mistake when using them 😄 😂
