### ISSUE TITLE
SIMD Harley-Seal Population Count

### ISSUE THREAD

**Issue by saik0** [RoaringBitmap/roaring-rs#165]
[arXiv:1709.07821](https://arxiv.org/abs/1709.07821) Roaring Bitmaps: Implementation of an Optimized Software Library (Section 4.1.1)

[arXiv:1611.07612](https://arxiv.org/abs/1611.07612) Faster Population Counts Using AVX2 Instructions
 > Our approach has been adopted by LLVM: it is used by its popular C compiler (clang).

Is this already done?

**Comment by Kerollmops** [comment]
I am pretty sure it hasn't been implemented.

**Comment by saik0** [comment]
> Our approach has been adopted by LLVM: it is used by its popular C compiler (clang).

llvm might be doing it for us :)

**Comment by saik0** [comment]
It does. Both for counting cardinality, and for counting while performing a set op.

https://godbolt.org/z/EKb3qvj5T
