### ISSUE TITLE
Branchless array-bitmap scalar operations

### ISSUE THREAD

**Issue by saik0** [RoaringBitmap/roaring-rs#206]
`@lemire` mentioned this in a talk.

https://youtu.be/1QMgGxiCFWE?t=1242

Could speed up [and](https://github.com/RoaringBitmap/roaring-rs/blob/d37d20242d55e8accc97999f7c6e99b71582e97c/src/bitmap/store/array_store/mod.rs#L313) [sub](https://github.com/RoaringBitmap/roaring-rs/blob/d37d20242d55e8accc97999f7c6e99b71582e97c/src/bitmap/store/array_store/mod.rs#L352)

**Comment by RaduBerinde** [comment]
I'd like to give this a shot.
