### ISSUE TITLE
Potential overflow when decoding in `RoaringBitmap::deserialize_from_impl()`

### ISSUE THREAD

**Issue by kirk-baird** [RoaringBitmap/roaring-rs#270]
# What is the issue

There is an overflow in [deserialize_from_impl()](https://github.com/RoaringBitmap/roaring-rs/blob/946bbfd1651c66da6e14d5eeed376ac9dbfc6f1b/src/bitmap/serialization.rs#L230) that can be reached if `s + len`  overflow a u16.

The overflow is reachable as both `s` and `len` are decoded from user input. 

Noting in release mode this will wrapping overflow and not cause a panic. However, a panic would occur in debug mode.

# What is the solution

Use checked math and propagate the error.

**Comment by Kerollmops** [comment]
Closed by #271
