### ISSUE TITLE
Remove documentation link

### ISSUE THREAD

**Issue by Nemo157** [RoaringBitmap/roaring-rs#64]
https://github.com/Nemo157/roaring-rs/blob/master/Cargo.toml#L7

It's not being auto-published anymore, and docs.rs is better anyway.

**Comment by Kerollmops** [comment]
You should always specify it, using https://docs.rs/roaring is enough but this way links are available on http://lib.rs or https://crates.io.

**Comment by Nemo157** [comment]
AFAIK crates.io defaults to docs.rs when it’s not specified.

**Comment by atouchet** [comment]
The link was changed to docs.rs in #104/#122. This can probably be closed now.

**Comment by Kerollmops** [comment]
You are right! Closing this!
