### ISSUE TITLE
Optimized Insert / Extend for sorted data

### ISSUE THREAD

**Issue by zommiommy** [RoaringBitmap/roaring-rs#69]
In my current use case, 65% of the time is spent doing the binary search inside of the `insert` method of `Store` but all the data are inserted in order.

Therefore, an optimized method for sorted values might speed-up this case.

I'm happy to help and I'm currently looking at the code to see If I'm able to fix it and submit a pull request.

**Comment by lemire** [comment]
@richardstartin worked on this for the Java version of Roaring.

See for example
https://github.com/RoaringBitmap/RoaringBitmap/pull/275

**Comment by zommiommy** [comment]
Thanks for answering! Currently, I have implemented a basic version [here](https://github.com/zommiommy/roaring-rs/tree/master).
There I have added a simple test and I'm currently testing and fuzzing it in my library. 
Later today I'll add some checks and documentation and I'll send a pull request.

Is there a preferred code style? (other than the default rust formatted)

**Comment by richardstartin** [comment]
I think the [original PR](https://github.com/RoaringBitmap/RoaringBitmap/pull/199) probably gives a cleaner diff to look at. The idea was that appending into a bitset and then converting into the right container before appending, which seems to work really well, but it's memory intensive if you're building millions of bitmaps at the same time. Then that was adapted to build a container and then run optimise/convert to the most efficient container prior to appending. Both these strategies avoid needing to call `runOptimize` after building the bitmap.
