### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by Nemo157** [RoaringBitmap/roaring-rs#72]
Given that I'm not using this library and don't really have time to review PRs for it, I would like to hand over maintainership to someone (or a group) that does and can care for it properly.

@Kerollmops it seems to me that you might be interested?

@lemire do you have any thoughts on moving this repo under the aegis of https://github.com/RoaringBitmap?

**Comment by Kerollmops** [comment]
@Nemo157 I would be glad to become the maintainer of this amazing library! It will be really cool if I can lead the library and would prefer if it could be moved in the https://github.com/RoaringBitmap, but that's up to @lemire :)

Thank you for proposing this to me!

**Comment by lemire** [comment]
Of course, moving it to the RoaringBitmap organization sounds like a good idea.

**Comment by lemire** [comment]
Please check your inboxes, you both have been invited to RoaringBitmap. If you become members, then you should be able to move the repo. there and work from there...

Note that if you want the org. to be displayed on your Github profile, you have to deliberately go and check a box. By default, membership to an org. is not outward visible.

Remember that I have free RoaringBitmap stickers (good for laptops and stuff). Just privately send me a mailing address.

**Comment by Nemo157** [comment]
:tada: and transferred.

@Kerollmops I have sent you an invite on crates.io so that you will be able to publish new versions, I don't remember whether it sends emails for that, but you should be able to accept it from <https://crates.io/me/pending-invites>.

There's a few links to https://nemo157.com/roaring-rs around, you probably want to replace those, but I'll setup a redirect there pointing directly to the repo.

You'll probably have to reconfigure CI as well (maybe migrate to GHA at the same time to get the better integration?).

**Comment by Kerollmops** [comment]
Thank you very much @Nemo157 🎉, I accepted the invitation and will take good care of your crate 😊
Will probably migrate the CI to Github actions like you say.

**Comment by lemire** [comment]
CI is probably the nastier thing to fix.

**Comment by Kerollmops** [comment]
@lemire I am just not sure why I don't see the repository settings? Maybe you can add me as a maintainer on it?

**Comment by Nemo157** [comment]
I think I hadn't configured anything, it was working off defaults. Looks like it has disappeared from my repositories list on https://app.bors.tech, so you probably have to re-enable it there if you want to use it (I'm not sure what happens to integrations during a repository transfer).

**Comment by Kerollmops** [comment]
Thank Nemo157, I requested the roaring-rs repository, I think I will be able to accept my own request when lemire making me a maintainer of the repo :)

I already moved the Travis settings to the Github Actions settings format and file, I'll try that.

**Comment by lemire** [comment]
I am taking care of it. I could not making you an admin on the project because... the project did not exist and you were not part of the org. Doing so now.

**Comment by lemire** [comment]
@Kerollmops You should have admin access now. From my reading of it, you are the sole admin of the project at this time. I also created a Rust Roaring "team", and we can add people to the team, and when doing so, they gain write access to the project so use that with care, only trusted folks should be in the 'team'.

<img width="995" alt="Screen Shot 2020-10-29 at 11 51 47 AM" src="https://user-images.githubusercontent.com/391987/97598264-238f6900-19dd-11eb-94b7-ad561be33f2d.png">

**Comment by Kerollmops** [comment]
Thank you Daniel, I will do that with care :)

**Comment by josephglanville** [comment]
I'm happy to contribute some time to reviewing code. My time availability isn't sufficient to be a maintainer but I have notifications enabled and watch issues/PRs and can help out where I can.
