### ISSUE TITLE
Copy the new Vec::retain implementation into the retain_mut function

### ISSUE THREAD

**Issue by Kerollmops** [RoaringBitmap/roaring-rs#87]
In some previous PRs (#83, #85), we introduced the retain_mut helper function that permits the modification of the visited elements by giving a `&mut` of the elements. [Now that the standard library `Vec::retain` function was rewritten](https://github.com/rust-lang/rust/pull/81126) and gives more than 20% performance improvement, it would be cool to patch our own function too!

**Comment by upsuper** [comment]
FWIW, you can use my crate [retain_mut](https://crates.io/crates/retain_mut). It hasn't updated the code, but I do plan to when the change reaches stable.

(Actually the change to Rust std was motivated by my inspect of the retain_mut crate for which I raised this inefficiency in a Rust group and another member decided to fix it :))
